spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB
  datasource:
    url: jdbc:postgresql://localhost:5432/playersdb
    username: salah
    password: salah123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: mcp-players-service
  main:
    web-application-type: servlet
    banner-mode: off
  ai:
    mcp:
      server:
        name: players-mcp-servers
        type: sync
        version: 1.0.0

media:
  upload-dir: uploads

jwt:
  secret: ZmFrZVNlY3JldEtleUZvckRldmVsb3BtZW50T25seURvTm90VXNlSW5Qcm9k
  expiration: 86400000
